import { supabase } from './supabaseClient';

export async function registerMember({
  fullName,
  indexNumber,
  program,
  level,
  phone,
  email,
  password,
}) {
  // 1. Create the auth user
  const { data: authData, error: authError } = await supabase.auth.signUp({
    email,
    password,
  });

  if (authError) throw authError;
  if (!authData.user) throw new Error('Sign up did not return a user.');

  // 2. Create their profile row (member_id auto-generated by trigger)
  const { data: profile, error: profileError } = await supabase
    .from('profiles')
    .insert({
      id: authData.user.id,
      full_name: fullName,
      index_number: indexNumber,
      program,
      level,
      phone,
      email,
      role: 'member',
    })
    .select()
    .single();

  if (profileError) throw profileError;

  return { user: authData.user, profile };
}


export async function loginMember({ email, password }) {
  const { data, error } = await supabase.auth.signInWithPassword({
    email,
    password,
  });
  if (error) throw error;
  return data;
}

export async function logout() {
  const { error } = await supabase.auth.signOut();
  if (error) throw error;
}


export async function getCurrentProfile() {
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) return null;

  const { data, error } = await supabase
    .from('profiles')
    .select('*')
    .eq('id', user.id)
    .single();

  if (error) throw error;
  return data;
}