import { supabase } from './supabaseClient';

/**
 * Register a new member.
 * Creates the auth user, then creates their profile row.
 * member_id (NEX-2026-XXX) is auto-generated by a DB trigger.
 */
export async function registerMember({ fullName, email, password, indexNumber, program, level, phone }) {
  const { data: authData, error: authError } = await supabase.auth.signUp({ email, password });
  if (authError) throw authError;
  if (!authData.user) throw new Error('Sign up did not return a user.');

  const { data: profile, error: profileError } = await supabase
    .from('profiles')
    .insert({
      id: authData.user.id,
      full_name: fullName,
      index_number: indexNumber ?? null,
      program: program ?? null,
      level: level ?? null,
      phone: phone ?? null,
      email,
      role: 'member',
    })
    .select()
    .single();

  if (profileError) throw profileError;
  return { user: authData.user, profile };
}

export async function loginMember({ email, password }) {
  const { data, error } = await supabase.auth.signInWithPassword({ email, password });
  if (error) throw error;
  return data;
}

export async function logout() {
  const { error } = await supabase.auth.signOut();
  if (error) throw error;
}

export async function getCurrentProfile() {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return null;

  let { data, error } = await supabase
    .from('profiles')
    .select('*')
    .eq('id', user.id)
    .single();

  // First-time Google sign-in: no profile row yet. Auto-create one so the
  // rest of the app (which always expects a profile) doesn't break.
  if (error && error.code === 'PGRST116') {
    const fullName = user.user_metadata?.full_name || user.user_metadata?.name || user.email.split('@')[0];
    const { data: created, error: createErr } = await supabase
      .from('profiles')
      .insert({ id: user.id, full_name: fullName, email: user.email, role: 'member' })
      .select()
      .single();
    if (createErr) throw createErr;
    return created;
  }

  if (error) throw error;
  return data;
}

/**
 * Sends a password reset email. The link in that email lands the user back
 * on /reset-password with a temporary recovery session already active.
 */
export async function requestPasswordReset(email) {
  const { error } = await supabase.auth.resetPasswordForEmail(email, {
    redirectTo: `${window.location.origin}/reset-password`,
  });
  if (error) throw error;
}

/**
 * Call this on the /reset-password page once the user has typed a new
 * password. Requires an active (recovery) session, which Supabase sets up
 * automatically when they land here via the emailed link.
 */
export async function updatePassword(newPassword) {
  const { error } = await supabase.auth.updateUser({ password: newPassword });
  if (error) throw error;
}

/**
 * Redirects the browser to Google's OAuth screen. On return, Supabase
 * establishes a session automatically and the user lands on /dashboard.
 * Requires the Google provider to be configured in the Supabase dashboard
 * (Authentication -> Providers -> Google) — see SETUP.md.
 */
export async function signInWithGoogle() {
  const { error } = await supabase.auth.signInWithOAuth({
    provider: 'google',
    options: { redirectTo: `${window.location.origin}/dashboard` },
  });
  if (error) throw error;
}